### ISSUE TITLE
Why don't you use Runnable instead of Executable class?

### ISSUE THREAD

**Issue by bigstark** [JSpiner/SafeExecutor#7]
# Question
## Why don't you use Runnable instead of Executable class?

I think you don't need to make a `Executable` class.  If it was my cases, I would use `Runnable` class for executing. Is there specific reason to use `Executable` class?

**Comment by JSpiner** [comment]
It's goood question. No, there is no reason.
I'll apply this issue.
Thanks!

**Comment by JSpiner** [comment]
it is implemented at #8
